#include <xar_engine/input/button.hpp>

#include <xar_engine/meta/enum_impl.hpp>


ENUM_TO_STRING_IMPL(xar_engine::input::ButtonCode,
                    xar_engine::input::ButtonCode::MOUSE_0,
                    xar_engine::input::ButtonCode::MOUSE_1,
                    xar_engine::input::ButtonCode::MOUSE_2,
                    xar_engine::input::ButtonCode::MOUSE_3,
                    xar_engine::input::ButtonCode::MOUSE_4,
                    xar_engine::input::ButtonCode::MOUSE_5,
                    xar_engine::input::ButtonCode::MOUSE_6,
                    xar_engine::input::ButtonCode::MOUSE_7,
                    xar_engine::input::ButtonCode::MOUSE_8,
                    xar_engine::input::ButtonCode::SPACE,
                    xar_engine::input::ButtonCode::_0,
                    xar_engine::input::ButtonCode::_1,
                    xar_engine::input::ButtonCode::_2,
                    xar_engine::input::ButtonCode::_3,
                    xar_engine::input::ButtonCode::_4,
                    xar_engine::input::ButtonCode::_5,
                    xar_engine::input::ButtonCode::_6,
                    xar_engine::input::ButtonCode::_7,
                    xar_engine::input::ButtonCode::_8,
                    xar_engine::input::ButtonCode::_9,
                    xar_engine::input::ButtonCode::A,
                    xar_engine::input::ButtonCode::B,
                    xar_engine::input::ButtonCode::C,
                    xar_engine::input::ButtonCode::D,
                    xar_engine::input::ButtonCode::E,
                    xar_engine::input::ButtonCode::F,
                    xar_engine::input::ButtonCode::G,
                    xar_engine::input::ButtonCode::H,
                    xar_engine::input::ButtonCode::I,
                    xar_engine::input::ButtonCode::J,
                    xar_engine::input::ButtonCode::K,
                    xar_engine::input::ButtonCode::L,
                    xar_engine::input::ButtonCode::M,
                    xar_engine::input::ButtonCode::N,
                    xar_engine::input::ButtonCode::O,
                    xar_engine::input::ButtonCode::P,
                    xar_engine::input::ButtonCode::Q,
                    xar_engine::input::ButtonCode::R,
                    xar_engine::input::ButtonCode::S,
                    xar_engine::input::ButtonCode::T,
                    xar_engine::input::ButtonCode::U,
                    xar_engine::input::ButtonCode::V,
                    xar_engine::input::ButtonCode::W,
                    xar_engine::input::ButtonCode::X,
                    xar_engine::input::ButtonCode::Y,
                    xar_engine::input::ButtonCode::Z,
                    xar_engine::input::ButtonCode::ESCAPE,
                    xar_engine::input::ButtonCode::ENTER,
                    xar_engine::input::ButtonCode::TAB,
                    xar_engine::input::ButtonCode::BACKSPACE);

ENUM_TO_STRING_IMPL(xar_engine::input::ButtonState,
                    xar_engine::input::ButtonState::DOWN,
                    xar_engine::input::ButtonState::REPEAT,
                    xar_engine::input::ButtonState::UP);
