#include <xar_engine/os/button.hpp>

#include <ostream>

#include <xar_engine/error/exception_utils.hpp>


ENUM_TO_STRING_IMPL(xar_engine::os::ButtonCode,
                    xar_engine::os::ButtonCode::MOUSE_0,
                    xar_engine::os::ButtonCode::MOUSE_1,
                    xar_engine::os::ButtonCode::MOUSE_2,
                    xar_engine::os::ButtonCode::MOUSE_3,
                    xar_engine::os::ButtonCode::MOUSE_4,
                    xar_engine::os::ButtonCode::MOUSE_5,
                    xar_engine::os::ButtonCode::MOUSE_6,
                    xar_engine::os::ButtonCode::MOUSE_7,
                    xar_engine::os::ButtonCode::MOUSE_8,
                    xar_engine::os::ButtonCode::SPACE,
                    xar_engine::os::ButtonCode::_0,
                    xar_engine::os::ButtonCode::_1,
                    xar_engine::os::ButtonCode::_2,
                    xar_engine::os::ButtonCode::_3,
                    xar_engine::os::ButtonCode::_4,
                    xar_engine::os::ButtonCode::_5,
                    xar_engine::os::ButtonCode::_6,
                    xar_engine::os::ButtonCode::_7,
                    xar_engine::os::ButtonCode::_8,
                    xar_engine::os::ButtonCode::_9,
                    xar_engine::os::ButtonCode::A,
                    xar_engine::os::ButtonCode::B,
                    xar_engine::os::ButtonCode::C,
                    xar_engine::os::ButtonCode::D,
                    xar_engine::os::ButtonCode::E,
                    xar_engine::os::ButtonCode::F,
                    xar_engine::os::ButtonCode::G,
                    xar_engine::os::ButtonCode::H,
                    xar_engine::os::ButtonCode::I,
                    xar_engine::os::ButtonCode::J,
                    xar_engine::os::ButtonCode::K,
                    xar_engine::os::ButtonCode::L,
                    xar_engine::os::ButtonCode::M,
                    xar_engine::os::ButtonCode::N,
                    xar_engine::os::ButtonCode::O,
                    xar_engine::os::ButtonCode::P,
                    xar_engine::os::ButtonCode::Q,
                    xar_engine::os::ButtonCode::R,
                    xar_engine::os::ButtonCode::S,
                    xar_engine::os::ButtonCode::T,
                    xar_engine::os::ButtonCode::U,
                    xar_engine::os::ButtonCode::V,
                    xar_engine::os::ButtonCode::W,
                    xar_engine::os::ButtonCode::X,
                    xar_engine::os::ButtonCode::Y,
                    xar_engine::os::ButtonCode::Z,
                    xar_engine::os::ButtonCode::ESCAPE,
                    xar_engine::os::ButtonCode::ENTER,
                    xar_engine::os::ButtonCode::TAB,
                    xar_engine::os::ButtonCode::BACKSPACE);

ENUM_TO_STRING_IMPL(xar_engine::os::ButtonState,
                    xar_engine::os::ButtonState::DOWN,
                    xar_engine::os::ButtonState::REPEAT,
                    xar_engine::os::ButtonState::UP);
